name: Build and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - build-actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [ 'arm64', 'x64' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Run linter
        run: dotnet format --verify-no-changes -v diag
      - name: Publish
        run: >-
          dotnet publish
          --configuration Release
          --runtime linux-${{ matrix.architecture }}
          --self-contained
          -p:SourceRevisionId=${{ github.sha }}
          --output ./dist-${{ matrix.architecture }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: totkbot-${{ matrix.architecture }}
          path: dist-${{ matrix.architecture }}
