name: Build and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - build-actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [ 'arm64', 'x64' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Run linter
        run: dotnet format --verify-no-changes -v diag
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Publish
        run: >-
          dotnet publish
          --configuration Release
          --runtime linux-${{ matrix.architecture }}
          --self-contained
          -p:SourceRevisionId=${{ steps.vars.outputs.sha_short }}
          --output ./dist-${{ matrix.architecture }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: totkbot-linux-${{ matrix.architecture }}
          path: dist-${{ matrix.architecture }}
      - name: Deploy
        uses: Burnett01/rsync-deployments@5.2.1
        if: ${{ matrix.architecture == 'arm64' }}
        with:
          switches: -avzr --delete
          path: dist-${{ matrix.architecture }}/*
          remote_path: /opt/totk
          remote_host: ${{ secrets.RSYNC_HOST }}
          remote_user: ${{ secrets.RSYNC_USER }}
          remote_key: ${{ secrets.RSYNC_KEY }}
      - name: Restart unit
        uses: appleboy/ssh-action@v0.1.10
        if: ${{ matrix.architecture == 'arm64' }}
        with:
          host: ${{ secrets.RSYNC_HOST }}
          username: ${{ secrets.RSYNC_USER }}
          key: ${{ secrets.RSYNC_KEY }}
          script: systemctl restart totkbot
